# Working docker-compose setup for causal cluster
# See the image tag for which version we're using.
#
# WARNING - PRIOR TO USING THIS SET UP LOCAL HOST ALIASES
# sudo vi /etc/hosts and then add these lines:
#
# 127.0.0.1	head
# 127.0.0.1	fabric1
# 127.0.0.1	fabric2
version: '3'

networks:
  lan:

services:
  head:
    image: neo4j:4.0.0-enterprise
    networks:
      - lan
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    volumes:
      - $HOME/neo4j/head/conf:/conf
      - $HOME/neo4j/head/data:/data
      - $HOME/neo4j/head/logs:/logs
      - $HOME/neo4j/head/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/admin
      - NEO4J_dbms_mode=SINGLE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_bolt_advertised__address=head:7687
      - NEO4J_dbms_memory_heap_initial__size=1024m
      - NEO4J_dbms_memory_heap_max__size=1024m
      - NEO4J_dbms_memory_pagecache_size=256m
      - NEO4J_dbms_directories_import=import
      - NEO4J_dbms_logs_query_enabled=INFO
      - NEO4J_dbms_logs_query_threshold=0s
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_fabric_routing_servers=neo4j://head:7687
      - NEO4J_fabric_database_name=fabric
      - NEO4J_fabric_graph_0_uri=neo4j://fabric1:7688
      - NEO4J_fabric_graph_0_database=city
      - NEO4J_fabric_graph_0_name=city
      - NEO4J_fabric_graph_1_uri=neo4j://fabric2:7689
      - NEO4J_fabric_graph_1_database=country
      - NEO4J_fabric_graph_1_name=country

  fabric1:
    image: neo4j:4.0.0-enterprise
    networks:
      - lan
    ports:
      - 7475:7475
      - 6478:6478      
      - 7688:7688      
    volumes:
      - $HOME/neo4j/fabric1/conf:/conf
      - $HOME/neo4j/fabric1/data:/data
      - $HOME/neo4j/fabric1/logs:/logs
      - $HOME/neo4j/fabric1/plugins:/plugins      
    environment:
      - NEO4J_AUTH=neo4j/admin
      - NEO4J_dbms_mode=SINGLE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_connector_http_listen__address=:7475
      - NEO4J_dbms_connector_https_listen__address=:6478
      - NEO4J_dbms_connector_bolt_listen__address=:7688
      - NEO4J_dbms_connector_bolt_advertised__address=fabric1:7688
      - NEO4J_config_strict__validation=true   
      - NEO4J_dbms_memory_heap_initial__size=1024m
      - NEO4J_dbms_memory_heap_max__size=1024m
      - NEO4J_dbms_memory_pagecache_size=256m
      - NEO4J_dbms_directories_import=import
      - NEO4J_dbms_logs_query_enabled=INFO
      - NEO4J_dbms_logs_query_threshold=0s
      - NEO4J_dbms_default__database=city
      
  fabric2:
    image: neo4j:4.0.0-enterprise
    networks:
      - lan
    ports:
      - 7476:7476
      - 6479:6479      
      - 7689:7689
    volumes:
      - $HOME/neo4j/fabric2/conf:/conf
      - $HOME/neo4j/fabric2/data:/data
      - $HOME/neo4j/fabric2/logs:/logs
      - $HOME/neo4j/fabric2/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/admin
      - NEO4J_dbms_mode=SINGLE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_connector_http_listen__address=:7476
      - NEO4J_dbms_connector_https_listen__address=:6479      
      - NEO4J_dbms_connector_bolt_listen__address=:7689
      - NEO4J_dbms_connector_bolt_advertised__address=fabric2:7689
      - NEO4J_config_strict__validation=true   
      - NEO4J_dbms_memory_heap_initial__size=1024m
      - NEO4J_dbms_memory_heap_max__size=1024m
      - NEO4J_dbms_memory_pagecache_size=256m
      - NEO4J_dbms_directories_import=import
      - NEO4J_dbms_logs_query_enabled=INFO
      - NEO4J_dbms_logs_query_threshold=0s
      - NEO4J_dbms_default__database=country
     